// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";

function Login(Props) {
  return React.createElement("section", {
              className: "section is-fullheight"
            }, React.createElement("div", {
                  className: "container"
                }, React.createElement("div", {
                      className: "columns is-centered"
                    }, React.createElement("div", {
                          className: "column is-half"
                        }, React.createElement("div", {
                              className: "field"
                            }, React.createElement("p", {
                                  className: "control has-icons-left has-icons-right"
                                }, React.createElement("input", {
                                      className: "input",
                                      placeholder: "Email",
                                      type: "email"
                                    }), React.createElement("span", {
                                      className: "icon is-small is-left"
                                    }, React.createElement("i", {
                                          className: "fas fa-envelope"
                                        })), React.createElement("span", {
                                      className: "icon is-small is-right"
                                    }, React.createElement("i", {
                                          className: "fas fa-check"
                                        })))), React.createElement("div", {
                              className: "field"
                            }, React.createElement("p", {
                                  className: "control has-icons-left"
                                }, React.createElement("input", {
                                      className: "input",
                                      placeholder: "Password",
                                      type: "password"
                                    }), React.createElement("span", {
                                      className: "icon is-small is-left"
                                    }, React.createElement("i", {
                                          className: "fas fa-lock"
                                        })))), React.createElement("div", {
                              className: "field"
                            }, React.createElement("p", {
                                  className: "control"
                                }, React.createElement("button", {
                                      className: "button is-success"
                                    }, "Login")))))));
}

var make = Login;

var $$default = Login;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
